/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package katas;

import katas.bank.BankMain;

public class App {
    public static void main(String[] args) {

        System.out.println("This is the main Class as defined in 'build.gradle.kts'");
        System.out.println("Let's run some transactions and print an account statement");
        new BankMain().run();
    }
}
