/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app;

import katas.bank.BankMain;
import multithreading.educativeio.ThreadSandbox;

public class App {
    public static void main(String[] args) throws Exception {
        new ThreadSandbox().runSandbox();
    }
}
