/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BankKataJava.sandbox;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;

import static org.junit.Assert.assertNotNull;


@RunWith(MockitoJUnitRunner.class)
public class AppTest {

    @Mock
    Printer printer;


    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void thisIsATest() {
        App classUnderTest = new App();
        classUnderTest.getGreeting();
    }

}
